# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl: 
url: https://cyendra.github.io
date_format: "ordinal"
title: my blog
author: cyendra

# ---------------- #
#   RSS / Email    #
# ---------------- #
subscribe_rss: /feed.xml
email:

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
paginate: 9
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment
comments_provider: gitment
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: cyendra
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: cyendra
    repo: cyendra.github.io
    oauth:
        client_id: 6e7518d0f1b3f3aa0829
        client_secret: 598238c66a1d3082d2fd61b86596e8524a5c31a5
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false
